// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(display)/bookmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookmarks">> = Specific
  const handler = {} as typeof import("../../src/app/(display)/bookmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(display)/finder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finder">> = Specific
  const handler = {} as typeof import("../../src/app/(display)/finder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(display)/listing/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/listing/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(display)/listing/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(display)/listing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/listing">> = Specific
  const handler = {} as typeof import("../../src/app/(display)/listing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(display)/recomended/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recomended">> = Specific
  const handler = {} as typeof import("../../src/app/(display)/recomended/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/reset/email/confirm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset/email/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/auth/reset/email/confirm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/reset/email/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset/email/request">> = Specific
  const handler = {} as typeof import("../../src/app/auth/reset/email/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/reset/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset/request">> = Specific
  const handler = {} as typeof import("../../src/app/auth/reset/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../src/app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/userinfo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/userinfo">> = Specific
  const handler = {} as typeof import("../../src/app/userinfo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/userpref/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/userpref">> = Specific
  const handler = {} as typeof import("../../src/app/userpref/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookmarks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookmarks">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookmarks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev/email-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/email-test">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev/email-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/finder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finder">> = Specific
  const handler = {} as typeof import("../../src/app/api/finder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hdbdata/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hdbdata">> = Specific
  const handler = {} as typeof import("../../src/app/api/hdbdata/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mrtdata/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mrtdata">> = Specific
  const handler = {} as typeof import("../../src/app/api/mrtdata/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reset/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reset/check">> = Specific
  const handler = {} as typeof import("../../src/app/api/reset/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reset/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reset/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/reset/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reset/email/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reset/email/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/reset/email/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reset/email/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reset/email/request">> = Specific
  const handler = {} as typeof import("../../src/app/api/reset/email/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/schooldataset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schooldataset">> = Specific
  const handler = {} as typeof import("../../src/app/api/schooldataset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test-db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-db">> = Specific
  const handler = {} as typeof import("../../src/app/api/test-db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/userinfo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/userinfo">> = Specific
  const handler = {} as typeof import("../../src/app/api/userinfo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
